### ISSUE TITLE
Upgrade to Node to 18 caused bitbucket pipeline issues with memfs

### ISSUE THREAD

**Issue by cjewvuit** [timbru31/docker-node-alpine-firefox#116]
```
31 10 2022 14:18:41.739:ERROR [karma-server]: UncaughtException: TypeError: Cannot set property closed of #<Readable> which has only a getter
    at FsReadStream.close (/opt/atlassian/pipelines/agent/build/services/web/angular/node_modules/memfs/lib/volume.js:2047:17)
    at FsReadStream._destroy (/opt/atlassian/pipelines/agent/build/services/web/angular/node_modules/memfs/lib/volume.js:2032:10)
    at _destroy (node:internal/streams/destroy:109:10)
    at class_1.destroy (node:internal/streams/destroy:71:5)
    at class_1.<anonymous> (/opt/atlassian/pipelines/agent/build/services/web/angular/node_modules/memfs/lib/volume.js:1962:22)
    at class_1.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by timbru31** [comment]
Thanks. Can you provide me a reproducible sample of your issue in order to narrow down the issue?

You can also downgrade to sha256:201a382e48aa475bd14395caa563877519c1b374dc0c65ca34f469542a9bab1a (last Node.js v16 image) in the meantime.

**Comment by timbru31** [comment]
The underlying issue is memfs: https://github.com/streamich/memfs/issues/828 - you probably want to upgrade your Angular version or rebuild your lockfiles in order to get a newer memfs version.
